### ISSUE TITLE
Hierarchical version?

### ISSUE THREAD

**Issue by invertdna** [nwfsc-cb/zoid#6]
This might be too hard to code in a general way, but might we/you make `zoid` hierarchical? 

For example, I have a dataset w 4 discrete temperature treatments (10, 13, 15, and 18 degrees C), with many observations in each; each observation is a set of proportions divided among 4 possible categories. If I treat temperature as a continuous predictor, I'm pretty sure `zoid` (and, for that matter, a linear model or anything similar) will have the pseudoreplication problem: each observation is treated as independent, when really what I should be doing is asking whether the *mean* of each treatment is responding to the predictor variable (here, temperature).  

If `zoid` could handle the syntax of `stan_glm` (or similar), we could do something like `formula = ~ treatment + (1 | group)`, and make it work for a more general class of problems. Just an idea.

**Comment by ericward-noaa** [comment]
See here: 
https://github.com/nwfsc-cb/zoid/commit/ca0e3da23d04d921fb19f6cf6d5bdb9b8521dffb
